#Coyote - Canis latrans - Cytochrome C oxidase subunit 1

c='MFINRWLFSTNHKDIGTLYLLFGAWAGMVGTALSLLIRAELGQPGTLLGDDQIYNVVVTAHAFVMIFFMVMPIMIGGFGNWLVPLMIGA'

#https://www.ncbi.nlm.nih.gov/nuccore/91702689


